modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/ZsoltMolnarrr/Archers/issues"

[[mods]]
modId="archers"
version="${version}"
displayName="Archers (RPG Series)"
authors="Daedelus"
description='''
Draw, Release, Conquer - Master the art of Archery!
'''
logoFile="icon.png"

[[dependencies.archers]]
modId="forge"
mandatory=true
versionRange="[47.4.23,)"
ordering="NONE"
side="BOTH"

[[dependencies.archers]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"

[[dependencies.archers]]
modId="armor_model_api"
mandatory=true
versionRange="[${armor_model_api_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.archers]]
modId="spell_engine"
mandatory=true
versionRange="[${spell_engine_version},)"
ordering="BEFORE"
side="BOTH"

[[dependencies.archers]]
modId="bundleapi"
mandatory=true
versionRange="[${bundle_api_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.archers]]
modId="ranged_weapon_api"
mandatory=true
versionRange="[${ranged_weapon_api_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.archers]]
modId="curios"
mandatory=false
versionRange="[${curios_version},)"
ordering="AFTER"
side="BOTH"

[[mixins]]
config="archers.mixins.json"
