modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="shield_api"
version="${version}"
displayName="Shield API"
description='''Shield API 2.1.0 behavior ported natively to Forge 1.20.1 for the RPG Series compatibility stack.'''

[[dependencies.shield_api]]
modId="forge"
mandatory=true
versionRange="[47.4.23,)"
ordering="NONE"
side="BOTH"

[[dependencies.shield_api]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
