#!/usr/bin/env bash
set -euo pipefail
ROOT="${GITHUB_WORKSPACE:?}"
PORT="$ROOT/rpg-series-port/rogues-forge-1.20.1"
TMP="${RUNNER_TEMP:-/tmp}/paladins-first-compile"
bash "$ROOT/rpg-series-port/ci/run-rogues-first-compile.sh"
pick_jar(){ local dir="$1" glob="$2" label="$3"; local -a jars=(); mapfile -t jars < <(find "$dir" -maxdepth 1 -type f -name "$glob" ! -name '*sources*' ! -name '*dev-shadow*' ! -name '*javadoc*' -print | sort); (( ${#jars[@]} == 1 )) || { echo "[Rogues acceptance] $label expected exactly one $glob in $dir, found ${#jars[@]}" >&2; return 1; }; printf '%s\n' "${jars[0]}"; }
stop_tree(){ local root="$1" child kids; kids="$(pgrep -P "$root" 2>/dev/null || true)"; for child in $kids; do stop_tree "$child"; done; kill -TERM "$root" 2>/dev/null || true; sleep 1; kill -KILL "$root" 2>/dev/null || true; wait "$root" 2>/dev/null || true; }
wait_for_log_marker(){ local pid="$1" deadline="$2" marker="$3" fatal="$4" primary="$5" latest="$6" label="$7"; local pass=0; while (( SECONDS < deadline )); do local -a files=("$primary"); [[ -f "$latest" ]] && files+=("$latest"); if grep -Eiq "$fatal" "${files[@]}" 2>/dev/null; then echo "[Rogues acceptance] $label fatal signature detected" >&2; tail -n 500 "${files[@]}" || true; stop_tree "$pid"; return 1; fi; if [[ -f "$latest" ]] && grep -Eq "$marker" "$latest"; then pass=1; break; fi; if ! kill -0 "$pid" 2>/dev/null; then wait "$pid" || true; tail -n 500 "${files[@]}" || true; echo "[Rogues acceptance] $label exited before marker: $marker" >&2; return 1; fi; sleep 1; done; if [[ "$pass" -ne 1 ]]; then local -a files=("$primary"); [[ -f "$latest" ]] && files+=("$latest"); tail -n 500 "${files[@]}" || true; stop_tree "$pid"; echo "[Rogues acceptance] $label timed out before marker: $marker" >&2; return 1; fi; stop_tree "$pid"; }
JAR="$(pick_jar "$PORT/forge/build/libs" '*-forge-*.jar' 'Rogues release')"; FIRST_SHA="$(sha256sum "$JAR" | awk '{print $1}')"; printf '%s  %s\n' "$FIRST_SHA" "$JAR" | tee "$PORT/rogues-first-build.sha256"
SPELL_POWER_COMMON="$(pick_jar "$ROOT/rpg-series-port/spell_power-forge-1.20.1/common/build/libs" '*-common-*.jar' 'Spell Power common')"; SPELL_POWER_FORGE="$(pick_jar "$ROOT/rpg-series-port/spell_power-forge-1.20.1/forge/build/libs" '*-forge-*.jar' 'Spell Power Forge')"; TINY_COMMON="$(pick_jar "$ROOT/rpg-series-port/tiny-config-forge-1.20.1/generated/common/build/libs" '*-common-*.jar' 'TinyConfig common')"; TINY_FORGE="$(pick_jar "$ROOT/rpg-series-port/tiny-config-forge-1.20.1/generated/forge/build/libs" '*-forge-*.jar' 'TinyConfig Forge')"; SPELL_ENGINE_COMMON="$(pick_jar "$ROOT/.spell-engine-build/common/build/libs" '*-common-*.jar' 'Spell Engine common')"; SPELL_ENGINE_FORGE="$ROOT/rpg-series-port/spell-engine-forge-1.20.1/spell_engine-forge-1.10.2+1.20.1.jar"; STRUCTURE_COMMON="$(pick_jar "$ROOT/rpg-series-port/structure_pool_api-forge-1.20.1/common/build/libs" '*-common-*.jar' 'Structure Pool common')"; STRUCTURE_FORGE="$(pick_jar "$ROOT/rpg-series-port/structure_pool_api-forge-1.20.1/forge/build/libs" '*-forge-*.jar' 'Structure Pool Forge')"; ARMOR_COMMON="$(pick_jar "$ROOT/rpg-series-port/armor-model-api-forge-1.20.1/generated/common/build/libs" '*-common-*.jar' 'Armor API common')"; ARMOR_FORGE="$(pick_jar "$ROOT/rpg-series-port/armor-model-api-forge-1.20.1/generated/forge/build/libs" '*-forge-*.jar' 'Armor API Forge')"; CLOTH_FORGE="$TMP/ext/cloth-config-forge-11.1.136.jar"; PLAYER_FORGE="$TMP/ext/player-animation-lib-forge-1.0.2+1.19.4.jar"; CURIOS_FORGE="$TMP/ext/curios-forge-5.14.1+1.20.1.jar"
for dep in "$SPELL_POWER_COMMON" "$SPELL_POWER_FORGE" "$TINY_COMMON" "$TINY_FORGE" "$SPELL_ENGINE_COMMON" "$SPELL_ENGINE_FORGE" "$STRUCTURE_COMMON" "$STRUCTURE_FORGE" "$ARMOR_COMMON" "$ARMOR_FORGE" "$CLOTH_FORGE" "$PLAYER_FORGE" "$CURIOS_FORGE"; do [[ -f "$dep" ]] || { echo "[Rogues acceptance] missing dependency: $dep" >&2; exit 1; }; unzip -tq "$dep" >/dev/null; done
ARGS=("-Parmor_model_api_common_jar=$ARMOR_COMMON" "-Pstructure_pool_api_common_jar=$STRUCTURE_COMMON" "-Pspell_power_common_jar=$SPELL_POWER_COMMON" "-Pspell_engine_common_jar=$SPELL_ENGINE_COMMON" "-Ptiny_config_common_jar=$TINY_COMMON" "-Parmor_model_api_forge_jar=$ARMOR_FORGE" "-Pstructure_pool_api_forge_jar=$STRUCTURE_FORGE" "-Pspell_power_forge_jar=$SPELL_POWER_FORGE" "-Pspell_engine_forge_jar=$SPELL_ENGINE_FORGE" "-Ptiny_config_forge_jar=$TINY_FORGE" "-Pcloth_config_forge_jar=$CLOTH_FORGE" "-Pplayer_animator_forge_jar=$PLAYER_FORGE" "-Pcurios_jar=$CURIOS_FORGE")
for rel in common/java/net/rogues/effect/RogueEffects.java common/java/net/rogues/entity/BearTrapEntity.java common/java/net/rogues/client/entity/BearTrapEntityRenderer.java common/java/net/rogues/mixin/LivingEntityStealth.java common/java/net/rogues/mixin/TrackTargetGoalStealth.java common/java/net/rogues/item/RogueWeapons.java common/java/net/rogues/item/armor/RogueArmors.java common/java/net/rogues/village/RogueVillagers.java; do test -f "$PORT/generated/$rel"; done
python3 - "$PORT/generated/common/resources" <<'PY'
from pathlib import Path
import json,sys
root=Path(sys.argv[1]); files=sorted(root.rglob('*.json'))
if len(files)<400: raise SystemExit(f'[Rogues acceptance] generated JSON inventory collapsed: {len(files)}')
for p in files: json.loads(p.read_text())
def load(name): return json.loads((root/'data/rogues/spell'/f'{name}.json').read_text())
vanish=load('vanish'); shock=load('shock_powder'); charge=load('charge'); trap=load('bear_trap')
assert vanish['impacts'][0]['action']['status_effect']['effect_id']=='rogues:stealth' and vanish['impacts'][0]['action']['status_effect']['duration']==8.0
assert shock['target']['type']=='AREA' and shock['impacts'][0]['action']['status_effect']['effect_id']=='rogues:shock' and shock['impacts'][0]['action']['status_effect']['duration']==2.0
assert charge['impacts'][0]['action']['status_effect']['effect_id']=='rogues:charge' and charge['impacts'][0]['action']['status_effect']['duration']==2.0
cloud=trap['deliver']['clouds'][0]; assert cloud['entity_type_id']=='rogues:bear_trap' and cloud['impact_cap']==1 and cloud['spawn_ticks']==20 and cloud['despawn_ticks']==15 and len(cloud['additional_placements'])==2
assert trap['impacts'][1]['action']['status_effect']['effect_id']=='rogues:bear_trap' and trap['impacts'][1]['action']['status_effect']['duration']==3.0
print(f'[Rogues acceptance] ROGUES_CURRENT_CONTENT_SEMANTIC_PASS: parsed {len(files)} JSON; Vanish/SHOCK Powder/Charge/Bear Trap current 3.1.1 contracts intact.')
PY
grep -Fq 'ActionImpairing.configure(SHOCK.effect, EntityActionsAllowed.STUN);' "$PORT/generated/common/java/net/rogues/effect/RogueEffects.java"; grep -Fq 'ActionImpairing.configure(BEAR_TRAP.effect, ROOT);' "$PORT/generated/common/java/net/rogues/effect/RogueEffects.java"; grep -Fq 'new EntityActionsAllowed(' "$PORT/generated/common/java/net/rogues/effect/RogueEffects.java"; grep -Fq 'beginDespawn(ATTACK_TICKS);' "$PORT/generated/common/java/net/rogues/entity/BearTrapEntity.java"; grep -Fq 'RogueEffects.STEALTH.effect' "$PORT/generated/common/java/net/rogues/mixin/TrackTargetGoalStealth.java"
echo '[Rogues acceptance] Clean reproducibility gate'; gradle --no-daemon --stacktrace -p "$PORT" clean :forge:remapJar "${ARGS[@]}"; JAR="$(pick_jar "$PORT/forge/build/libs" '*-forge-*.jar' 'clean Rogues release')"; SECOND_SHA="$(sha256sum "$JAR" | awk '{print $1}')"; printf '%s  %s\n' "$SECOND_SHA" "$JAR" | tee "$PORT/rogues.sha256"; [[ "$FIRST_SHA" = "$SECOND_SHA" ]] || { echo "[Rogues acceptance] non-reproducible release: first=$FIRST_SHA second=$SECOND_SHA" >&2; exit 1; }; [[ "$SECOND_SHA" = '9e8c880f55ab57d91148c0be702a431bad6e312900b25f65c9dbec266e3ca401' ]] || { echo "[Rogues acceptance] release drifted from run #217 authority: $SECOND_SHA" >&2; exit 1; }; unzip -tq "$JAR" >/dev/null; unzip -p "$JAR" META-INF/mods.toml | grep -F 'modId="rogues"' >/dev/null; if unzip -Z1 "$JAR" | grep -E '^(net/spell_engine/|net/spell_power/|net/fabric_extras/structure_pool/|net/rpg_foundation/armor_api/|net/tiny_config/)'; then echo '[Rogues acceptance] external foundation classes leaked into release' >&2; exit 1; fi; echo "[Rogues acceptance] reproducible release SHA-256: $SECOND_SHA"
SOURCE_ZIP="$ROOT/rogues-3.1.1-forge-1.20.1-source-ci.zip"; rm -f "$SOURCE_ZIP"
python3 - "$PORT" "$SOURCE_ZIP" <<'PY'
from pathlib import Path
import stat,sys,zipfile
src=Path(sys.argv[1]).resolve(); out=Path(sys.argv[2]).resolve(); skip={'.gradle','build','run','runs','.git','.upstream','.fresh-rogues-forge-server'}; files=[]
for p in src.rglob('*'):
    rel=p.relative_to(src)
    if any(x in skip for x in rel.parts): continue
    if len(rel.parts)==1 and rel.name.startswith('rogues') and rel.suffix=='.sha256': continue
    if len(rel.parts)==1 and (rel.name.endswith('-smoke.log') or rel.name.endswith('-behavior.log') or rel.name.endswith('-server.log') or rel.name.endswith('-xvfb.log')): continue
    if p.is_file(): files.append((rel.as_posix(),p))
with zipfile.ZipFile(out,'w',compression=zipfile.ZIP_DEFLATED,compresslevel=9) as zf:
    for arc,p in sorted(files):
        info=zipfile.ZipInfo(arc,date_time=(1980,1,1,0,0,0)); info.compress_type=zipfile.ZIP_DEFLATED; info.external_attr=(stat.S_IFREG|0o644)<<16; info.create_system=3; zf.writestr(info,p.read_bytes(),compress_type=zipfile.ZIP_DEFLATED,compresslevel=9)
PY
unzip -tq "$SOURCE_ZIP" >/dev/null; SOURCE_SHA="$(sha256sum "$SOURCE_ZIP" | awk '{print $1}')"; printf '%s  %s\n' "$SOURCE_SHA" "$SOURCE_ZIP" | tee "$PORT/rogues-source.sha256"
echo '[Rogues acceptance] Dedicated Forge dev-server gate'; rm -rf "$PORT/forge/run/logs"; mkdir -p "$PORT/forge/run"; printf 'eula=true\n' > "$PORT/forge/run/eula.txt"; SERVER_SMOKE="$PORT/rogues-server-smoke.log"; : > "$SERVER_SMOKE"; ( gradle --no-daemon -p "$PORT" :forge:runServer "${ARGS[@]}" ) > "$SERVER_SMOKE" 2>&1 & SERVER_PID=$!; SERVER_LATEST="$PORT/forge/run/logs/latest.log"; FATAL_SERVER='MixinApplyError|InvalidMixinException|MixinTransformerError|Failed to create mod instance|NoClassDefFoundError|ClassNotFoundException|Missing or unsupported mandatory dependencies|Registry is already frozen|Can not register to a locked registry|Exception in server tick loop|The game crashed'; wait_for_log_marker "$SERVER_PID" "$((SECONDS+210))" 'Done \([0-9.]+s\)!' "$FATAL_SERVER" "$SERVER_SMOKE" "$SERVER_LATEST" 'dev server'; echo '[Rogues acceptance] Dedicated Forge dev server reached ready state.'
echo '[Rogues acceptance] Headless Forge client/resource/render bootstrap gate'; rm -rf "$PORT/forge/run/logs"; mkdir -p "$PORT/forge/run/config"; printf 'earlyWindowControl = false\n' > "$PORT/forge/run/config/fml.toml"; CLIENT_SMOKE="$PORT/rogues-client-smoke.log"; : > "$CLIENT_SMOKE"; ( env LIBGL_ALWAYS_SOFTWARE=1 MESA_LOADER_DRIVER_OVERRIDE=llvmpipe xvfb-run -a -s '-screen 0 1280x720x24 +extension GLX +extension RENDER -noreset' gradle --no-daemon -p "$PORT" :forge:runClient "${ARGS[@]}" </dev/null ) > "$CLIENT_SMOKE" 2>&1 & CLIENT_PID=$!; CLIENT_LATEST="$PORT/forge/run/logs/latest.log"; FATAL_CLIENT='MixinApplyError|InvalidMixinException|MixinTransformerError|Failed to create mod instance|NoClassDefFoundError|ClassNotFoundException|The game crashed whilst initializing game|Exception in thread "Render thread"|Failed to initialize graphics window|Timed out trying to setup the Game Window|Could not initialize GLFW|Missing or unsupported mandatory dependencies|Using missing texture.*rogues|Failed to load model.*rogues|Unable to load model.*rogues'; wait_for_log_marker "$CLIENT_PID" "$((SECONDS+210))" 'Reloading ResourceManager' "$FATAL_CLIENT" "$CLIENT_SMOKE" "$CLIENT_LATEST" 'headless client'; grep -Fq 'Backend library: LWJGL' "$CLIENT_LATEST" || { tail -n 500 "$CLIENT_LATEST"; echo '[Rogues acceptance] client marker occurred without LWJGL backend evidence' >&2; exit 1; }; echo '[Rogues acceptance] Headless client reached post-bootstrap resource/render runtime with LWJGL, including Bear Trap renderer registration.'
FRESH="$PORT/.fresh-rogues-forge-server"; rm -rf "$FRESH"; mkdir -p "$FRESH"; curl --retry 2 --retry-delay 1 -fsSL 'https://maven.minecraftforge.net/net/minecraftforge/forge/1.20.1-47.4.23/forge-1.20.1-47.4.23-installer.jar' -o "$FRESH/forge-installer.jar"; ( cd "$FRESH"; java -jar forge-installer.jar --installServer >/dev/null; printf 'eula=true\n' > eula.txt; printf '%s\n' '-Xmx2G' > user_jvm_args.txt; cat > server.properties <<'PROPS'
level-type=minecraft:flat
generate-structures=false
view-distance=3
simulation-distance=3
spawn-protection=0
online-mode=false
PROPS
mkdir -p mods; cp "$JAR" "$ARMOR_FORGE" "$STRUCTURE_FORGE" "$SPELL_POWER_FORGE" "$SPELL_ENGINE_FORGE" "$TINY_FORGE" "$CLOTH_FORGE" "$PLAYER_FORGE" "$CURIOS_FORGE" mods/ ); [[ "$(find "$FRESH/mods" -maxdepth 1 -type f -name '*.jar' | wc -l | tr -d ' ')" = 9 ]] || { find "$FRESH/mods" -maxdepth 1 -type f -name '*.jar' -printf '%f\n' | sort >&2; echo '[Rogues acceptance] packaged server runtime mod count mismatch' >&2; exit 1; }; INSTALLED="$FRESH/mods/$(basename "$JAR")"; cmp -s "$JAR" "$INSTALLED"; sha256sum "$INSTALLED" | tee "$PORT/rogues-package-installed.sha256"; PACKAGE_LOG="$PORT/rogues-package-server-smoke.log"; : > "$PACKAGE_LOG"; ( cd "$FRESH" && exec ./run.sh nogui ) > "$PACKAGE_LOG" 2>&1 & PACKAGE_PID=$!; PACKAGE_LATEST="$FRESH/logs/latest.log"; FATAL_PACKAGE='ModLoadingException|Failed to create mod instance|Failed to start the minecraft server|NoClassDefFoundError|ClassNotFoundException|MixinApplyError|InvalidMixinException|MixinTransformerError|Registry is already frozen|Can not register to a locked registry|Missing or unsupported mandatory dependencies|Exception in server tick loop|The game crashed'; wait_for_log_marker "$PACKAGE_PID" "$((SECONDS+180))" 'Done \([0-9.]+s\)!' "$FATAL_PACKAGE" "$PACKAGE_LOG" "$PACKAGE_LATEST" 'fresh packaged server'; echo '[Rogues acceptance] Fresh packaged Forge 47.4.23 server reached ready state with exact Rogues release + eight separate runtime dependencies.'; echo '[Rogues acceptance] FULL_ACCEPTANCE_PASS: reproducible release, deterministic source, current-content semantics, dev server, native LWJGL client, and fresh packaged server.'
