#!/usr/bin/env bash
set -euo pipefail
ROOT="${GITHUB_WORKSPACE:?}"
PORT="$ROOT/rpg-series-port/paladins-forge-1.20.1"
QA_SRC="$PORT/forge/src/main/java/net/paladins/forge/client/qa/PaladinsQaAutoConnect.java"

cleanup(){ rm -f "$QA_SRC"; rmdir --ignore-fail-on-non-empty "$(dirname "$QA_SRC")" 2>/dev/null || true; }
trap cleanup EXIT
mkdir -p "$(dirname "$QA_SRC")"
cat > "$QA_SRC" <<'JAVA'
package net.paladins.forge.client.qa;

import net.minecraft.client.MinecraftClient;
import net.minecraft.client.gui.screen.ConnectScreen;
import net.minecraft.client.network.ServerAddress;
import net.minecraft.client.network.ServerInfo;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.event.TickEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import net.paladins.PaladinsMod;

/** QA-only source generated by CI and removed after the native-client run. */
@Mod.EventBusSubscriber(modid = PaladinsMod.ID, bus = Mod.EventBusSubscriber.Bus.FORGE, value = Dist.CLIENT)
public final class PaladinsQaAutoConnect {
    private static int ticks;
    private static boolean dispatched;

    private PaladinsQaAutoConnect() { }

    @SubscribeEvent
    public static void onClientTick(TickEvent.ClientTickEvent event) {
        if (event.phase != TickEvent.Phase.END || dispatched) return;
        MinecraftClient client = MinecraftClient.getInstance();
        if (client.player != null || client.currentScreen == null) return;
        if (++ticks < 120) return;

        dispatched = true;
        ServerInfo info = new ServerInfo("Paladins QA", "127.0.0.1:25565", false);
        System.out.println("[Paladins player QA] PALADINS_QA_AUTOCONNECT_DISPATCHED: invoking Minecraft 1.20.1 ConnectScreen against 127.0.0.1:25565.");
        ConnectScreen.connect(client.currentScreen, client, ServerAddress.parse(info.address), info, false);
    }
}
JAVA

# Fail closed: the helper must remain an ephemeral CI source and the committed product tree must
# not contain it. The release/source identities are certified before this wrapper runs.
grep -Fq 'PALADINS_QA_AUTOCONNECT_DISPATCHED' "$QA_SRC"
echo '[Paladins player QA] DETERMINISTIC_AUTOCONNECT_HARNESS_READY: QA-only client hook generated outside committed product history.'

bash "$ROOT/rpg-series-port/ci/run-paladins-player-behavior-acceptance.sh"
